version: '2'
services:
  control:
    build: control
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - ${workdir}:/opt/ansible
      - ${SSH_AGENT_PATH}:/ssh-agent
    links:
      - debian:debian
      - centos:centos
  debian:
    build: node-debian
    environment:
      - AUTHORIZED_KEYS=${KEYS}
  centos:
    build: node-centos
    environment:
      - AUTHORIZED_KEYS=${KEYS}

